version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: wordpress_nextjs_mysql_db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - wordpress_nextjs_network_app

  wordpress:
    build:
      context: ./wordpress-api
      dockerfile: Dockerfile
    container_name: wordpress_app
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      - wordpress_nextjs_network_app

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.next
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - wordpress
    networks:
      - wordpress_nextjs_network_app

networks:
  wordpress_nextjs_network_app:
    driver: bridge
